# Maven
- task: Docker@2
  inputs:
    containerRegistry: 'udemy dock2'
    command: 'login'
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: Docker@2
  inputs:
    containerRegistry: 'udemy dock2'
    repository: 'AzureDockerfile'
    command: 'buildAndPush'
    Dockerfile: '**/AzureDockerfile'